{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-preview-operator.fullname" . }}-metrics
  labels:
    {{- include "homelab-preview-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "homelab-preview-operator.selectorLabels" . | nindent 4 }}
{{- end }}
